### ISSUE TITLE
Building too often results in rate limit

### ISSUE THREAD

**Issue by jamesthesken** [staticfloat/docker-nginx-certbot#32]
While developing on top of the sample `docker-compose.yml` file found in the `example` directory, I hit the rate limit for Certbot after using `docker-compose up` too often:

```
acme.messages.Error: urn:ietf:params:acme:error:rateLimited :: There were too many requests of a given type :: Error creating new order :: too many certificates already issued for exact set of domains: mqtt.autofarm.app: see https://letsencrypt.org/docs/rate-limits/
```

Is there a way to check if the certifications have been made before running the renewal script? 

Thank you for this repo!

**Comment by fredrikekre** [comment]
The code does check if the certificate needs renewal before requesting it, so you just need to make sure you preserve the recieved certificate between docker starts, e.g. by mounting a volume. This is what I use for example:
```
services:
 nginx:
    image: staticfloat/nginx-certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
    # etc
volumes:
  letsencrypt: # letsencrypt certificates
```
